version : '3'
services:
  bdap:
    image: focal:bdap
    tty: true
    stdin_open: true
    volumes:
     - /Users/$userID/born_digital/$uuid:/Users/borndigital/born_digital/$uuid
     - /Volumes:/Volumes:ro
    user: tuffy
