version : '3'
services:
  bdap:
    image: focal:bdap
    tty: true
    stdin_open: true
    # volumes:
    #  - ${BDAP_STORAGE_VOLUME_SOURCE:-/Users/$userID/born_digital/$uuid}:${BDAP_STORAGE_VOLUME_TARGET:-/Users/borndigital/born_digital/$uuid}
    #  - /Volumes:/Volumes:ro
    user: $userID
